ecs-publication:
    build: .
    container_name: "ecs-publication"
    net: "host"
    volumes:
        - /home/vagrant:/home/developer
    user: 1000:1000
    environment:
        ORG_GRADLE_PROJECT_artifactGroup: org.devan
