ecs-publication:
    build: .
    container_name: "ecs-publication"
    net: "host"
    volumes:
        - /home/vagrant:/home/developer
        - /home/vagrant/GitHub/docker-ecs-publication/templates:/templates
    user: 1000:1000
    environment:
        ORG_GRADLE_PROJECT_artifactGroup: org.kurron
        ORG_GRADLE_PROJECT_major: 1
        ORG_GRADLE_PROJECT_minor: 2
        ORG_GRADLE_PROJECT_patch: 3
        ORG_GRADLE_PROJECT_branch: master
        ORG_GRADLE_PROJECT_family: Alpha
        ORG_GRADLE_PROJECT_containerName: Bravo
        ORG_GRADLE_PROJECT_registry: Charlie
        ORG_GRADLE_PROJECT_imageName: Delta
        ORG_GRADLE_PROJECT_imageTag: Echo
        ORG_GRADLE_PROJECT_clusterName: Foxtrot
        ORG_GRADLE_PROJECT_serviceName: Golf
        ORG_GRADLE_PROJECT_loadBalancerName: Hotel
        ORG_GRADLE_PROJECT_clientToken: India
        ORG_GRADLE_PROJECT_ecsInstanceRole: Juliett
        ORG_GRADLE_PROJECT_desiredCount: Kilo

